services:
  # MongoDB Database Service
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=securepassword
    volumes:
      - mongodb_tbas_data:/data/db
    networks:
      - tbas_network

  # Backend API Service
  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "5129:80"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PROD_API_KEY=${PROD_API_KEY}
    env_file:
      - .env
    networks:
      - tbas_network

  # Frontend Web Service
  frontend:
    build:
      context: Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_API_KEY=${VITE_API_KEY}
    env_file:
      - Frontend/.env
    networks:
      - tbas_network

# Docker Network Configuration
networks:
  tbas_network:
    driver: bridge

# Persistent Volume Configuration
volumes:
  mongodb_tbas_data:
    name: tbas_mongodb_data