services:
  mongodb:
      container_name: tbas_mongodb
      image: mongo:latest
      ports:
        - "27017:27017"
      environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=securepassword
        - MONGO_INITDB_DATABASE=tbas_db
      volumes:
        - mongodb_tbas_data:/data/db
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      command: mongod --auth
      networks:
        - tbas_network

  backend:
    container_name: tbas_backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      - LOGGING__LOGLEVEL__DEFAULT=Debug
      - LOGGING__LOGLEVEL__MICROSOFT=Debug
      - ENV_FILE_PATH=${ENV_FILE_PATH:-./.env}
    ports:
      - "5129:5129"
    env_file:
      - ${BACKEND_ENV_FILE:-./.env}
    depends_on:
      - mongodb
    networks:
      - tbas_network

  frontend:
    container_name: tbas_frontend
    build:
      context: Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - ${FRONTEND_ENV_FILE:-Frontend/.env}
    depends_on:
      - backend
    networks:
      - tbas_network

networks:
  tbas_network:
    driver: bridge

volumes:
  mongodb_tbas_data:
    name: tbas_mongodb_data