services:
  # MongoDB Database Service
  mongodb:
    container_name: tbas_mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ADMIN_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - mongodb_tbas_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - tbas_network
    restart: unless-stopped

  # Backend API Service
  backend:
    container_name: tbas_backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
      args:
        BUILD_VERSION: ${BUILD_VERSION:-local}
    ports:
      - "5129:5129"
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - tbas_network
    restart: unless-stopped

  # Frontend Web Service
  frontend:
    container_name: tbas_frontend
    build:
      context: Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - Frontend/.env
    networks:
      - tbas_network
    restart: unless-stopped

# Docker Network Configuration
networks:
  tbas_network:
    driver: bridge

# Persistent Volume Configuration
volumes:
  mongodb_tbas_data:
    name: tbas_mongodb_data