services:
  mongodb:
    container_name: tbas_mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ADMIN_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - mongodb_tbas_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - tbas_network
    restart: unless-stopped

  backend:
    container_name: tbas_backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      CORS_ENABLED: "true"
      CORS_ORIGIN: "http://${AZURE_VM_IP}"
      CORS_METHODS: "GET,POST,OPTIONS,DELETE"
      CORS_ALLOWED_HEADERS: "Content-Type,Authorization"
      CORS_EXPOSED_HEADERS: "Content-Length,Content-Range"
      MONGODB_HOST: "mongodb"
      API_KEY: ${API_KEY}
      MONGODB_URI: ${MONGODB_URI}
    ports:
      - "5129:5129"
    depends_on:
      - mongodb
    networks:
      - tbas_network
    restart: unless-stopped


  frontend:
    container_name: tbas_frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile
      args:
        - VITE_API_KEY=${API_KEY}
        - VITE_AZURE_VM_URL=http://${AZURE_VM_IP}/api
    environment:
      - VITE_API_KEY=${API_KEY}
      - VITE_AZURE_VM_URL=http://${AZURE_VM_IP}/api
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - tbas_network
    restart: unless-stopped

networks:
  tbas_network:
    driver: bridge

volumes:
  mongodb_tbas_data:
    name: tbas_mongodb_data