- name: Deploy Application
  hosts: app_server
  become: yes
  vars:
    build_version: "{{ lookup('env', 'GITHUB_SHA') | default(lookup('pipe', 'date +%Y%m%d%H%M%S'), true) }}"
  tasks:
    - name: Verifiera app-mapp finns
      stat:
        path: /app
      register: app_dir

    - name: Stoppa existerande containers
      community.docker.docker_compose_v2:
        project_src: /app
        state: absent
        remove_volumes: true
      ignore_errors: yes

    - name: Skapa miljöfiler
      block:
        - name: Backend .env
          copy:
            content: |
              MONGODB_URI="mongodb://{{ lookup('env', 'MONGODB_USER') }}:{{ lookup('env', 'MONGODB_PASSWORD') }}@mongodb:27017/{{ lookup('env', 'MONGODB_DATABASE') }}?authSource=admin"
              API_KEY="{{ lookup('env', 'API_KEY') }}"
              MONGODB_ADMIN="{{ lookup('env', 'MONGODB_ADMIN') }}"
              MONGODB_ADMIN_PASSWORD="{{ lookup('env', 'MONGODB_ADMIN_PASSWORD') }}"
              MONGODB_DATABASE="{{ lookup('env', 'MONGODB_DATABASE') }}"
            dest: /app/.env
            mode: '0600'

        - name: Frontend .env
          copy:
            content: |
              VITE_API_BASE_URL="http://{{ lookup('env', 'AZURE_VM_IP') }}/api"
              VITE_API_KEY="{{ lookup('env', 'API_KEY') }}"
            dest: /app/Frontend/.env
            mode: '0600'

    - name: Starta Docker Compose
      community.docker.docker_compose_v2:
        project_src: /app
        files:
          - docker-compose.yml
        build: never  # Viktigt! Vi vill inte bygga om
        pull: always
        remove_orphans: true
        state: present
        env_files:
          - /app/.env
          - /app/Frontend/.env