- name: Deploy Application
  hosts: app_server
  become: yes
  vars:
    build_version: "{{ lookup('env', 'GITHUB_SHA') | default(lookup('pipe', 'date +%Y%m%d%H%M%S'), true) }}"
    debug_mode: "{{ lookup('env', 'DEBUG_MODE') | default(false) }}"
  tasks:

    - name: Kontrollera att nödvändiga filer och mappar finns
      stat:
        path: "{{ item }}"
      register: file_checks
      with_items:
        - /app/Frontend
        - /app/docker-compose.yml

    - name: Stoppa om Frontend-mappen saknas
      fail:
        msg: "Frontend directory is missing"
      when: not file_checks.results[0].stat.isdir

    - name: Stoppa och ta bort existerande containers
      community.docker.docker_compose_v2:
        project_src: /app
        state: absent
        remove_volumes: true
      ignore_errors: yes

    - name: Skapa Backend .env-fil
      copy:
        content: |
          MONGODB_URI="mongodb://{{ lookup('env', 'MONGODB_USER') }}:{{ lookup('env', 'MONGODB_PASSWORD') }}@mongodb:27017/{{ lookup('env', 'MONGODB_DATABASE') }}?authSource=admin"
          API_KEY="{{ lookup('env', 'API_KEY') }}"
          MONGODB_ADMIN="{{ lookup('env', 'MONGODB_ADMIN') }}"
          MONGODB_ADMIN_PASSWORD="{{ lookup('env', 'MONGODB_ADMIN_PASSWORD') }}"
          MONGODB_DATABASE="{{ lookup('env', 'MONGODB_DATABASE') }}"
          BUILD_VERSION="{{ build_version }}"
        dest: /app/.env
        mode: '0600'

    - name: Skapa Frontend .env-fil
      copy:
        content: |
          VITE_API_BASE_URL="http://{{ lookup('env', 'AZURE_VM_IP') }}/api"
          VITE_API_KEY="{{ lookup('env', 'API_KEY') }}"
          VITE_BUILD_VERSION="{{ build_version }}"
        dest: /app/Frontend/.env
        mode: '0600'

    - name: Bygg och starta upp Docker Compose v2
      community.docker.docker_compose_v2:
        project_src: /app
        files:
          - docker-compose.yml
        build: always
        pull: always
        remove_orphans: true
        remove_volumes: false
        state: present
        env_files:
          - /app/.env
          - /app/Frontend/.env