- name: Deploy Application
  hosts: app_server
  become: yes
  tasks:
    - name: Create app directory
      file:
        path: /app
        state: directory
        owner: azureuser
        group: azureuser
        mode: '0755'

    - name: Copy application files
      copy:
        src: ./
        dest: /app/
        owner: azureuser
        group: azureuser
        mode: preserve

    - name: Check if backend .env file exists
      stat:
        path: .env
      register: backend_env_file

    - name: Ensure .env file for backend
      copy:
        src: .env
        dest: /app/.env
        owner: azureuser
        group: azureuser
        mode: '0600'
      when: backend_env_file.stat.exists

    - name: Ensure .env file permissions for backend
      file:
        path: /app/.env
        mode: '0600'
        owner: azureuser
        group: azureuser

    - name: Check if frontend .env file exists
      stat:
        path: Frontend/.env
      register: frontend_env_file

    - name: Ensure .env file for frontend
      copy:
        src: Frontend/.env
        dest: /app/Frontend/.env
        owner: azureuser
        group: azureuser
        mode: '0600'
      when: frontend_env_file.stat.exists

    - name: Ensure .env file permissions
      file:
        path: /app/Frontend/.env
        mode: '0600'
        owner: azureuser
        group: azureuser

    - name: Create appsettings.Production.json from template
      template:
        src: templates/appsettings.Production.json.j2
        dest: /app/Backend/appsettings.Production.json
        mode: '0644'
        owner: azureuser
        group: azureuser
      vars:
        app_ip: "{{ lookup('env', 'VM_IP') }}"
        mongodb_uri: "{{ lookup('env', 'MONGODB_URI') }}"
        api_key: "{{ lookup('env', 'API_KEY') }}"

    - name: Start Docker Compose
      community.docker.docker_compose_v2:
        project_src: /app
        files:
          - docker-compose.yml
        state: present
        env:
          BACKEND_ENV_FILE: /app/.env
          FRONTEND_ENV_FILE: /app/Frontend/.env