- name: Deploy Application
  hosts: app_server
  become: yes
  vars:
    build_version: "{{ lookup('env', 'GITHUB_SHA') | default(lookup('pipe', 'date +%Y%m%d%H%M%S'), true) }}"
    debug_mode: "{{ lookup('env', 'DEBUG_MODE') | default(false) }}"
  tasks:
    # Skip file copying since Act already does it
    - name: Verify Frontend directory exists
      stat:
        path: /app/Frontend
      register: frontend_dir

    # Fail if Frontend directory is missing
    - name: Fail if Frontend directory is missing
      fail:
        msg: "Frontend directory is missing"
      when: not frontend_dir.stat.isdir

    # Verify Backend directory exists
    - name: Stop and remove existing containers
      community.docker.docker_compose:
        project_src: /app
        state: absent
        remove_volumes: yes
      ignore_errors: yes

    # DEBUG - kan tas bort senare
    - name: Debug all environment variables
      ansible.builtin.debug:
        msg: |
          All environment variables:
          Build version: {{ build_version }}
          MONGODB_URI: {{ lookup('env', 'MONGODB_URI') }}
          MONGODB_DATABASE: {{ lookup('env', 'MONGODB_DATABASE') }}
          MONGODB_ADMIN: {{ lookup('env', 'MONGODB_ADMIN') }}
          MONGODB_ADMIN_PASSWORD: {{ lookup('env', 'MONGODB_ADMIN_PASSWORD') }}
          API_KEY: {{ lookup('env', 'API_KEY') }}

    # Create environment files
    - name: Create Backend .env file
      copy:
        content: |
          MONGODB_URI="mongodb://{{ lookup('env', 'MONGODB_USER') }}:{{ lookup('env', 'MONGODB_PASSWORD') }}@mongodb:27017/{{ lookup('env', 'MONGODB_DATABASE') }}?authSource=admin"
          API_KEY="{{ lookup('env', 'API_KEY') }}"
          MONGODB_ADMIN="{{ lookup('env', 'MONGODB_ADMIN') }}"
          MONGODB_ADMIN_PASSWORD="{{ lookup('env', 'MONGODB_ADMIN_PASSWORD') }}"
          MONGODB_DATABASE="{{ lookup('env', 'MONGODB_DATABASE') }}"
          BUILD_VERSION="{{ build_version }}"
        dest: /app/.env
        mode: '0600'
        owner: azureuser
        group: azureuser

    # DEBUG - kan tas bort senare
    - name: Display created .env contents
      ansible.builtin.shell: cat /app/.env
      register: env_contents

    # DEBUG - kan tas bort senare
    - name: Show .env contents
      debug:
        var: env_contents.stdout_lines

    # Create environment files
    - name: Create Frontend .env file
      copy:
        content: |
          VITE_API_BASE_URL="http://{{ lookup('env', 'AZURE_VM_IP') }}/api"
          VITE_API_KEY="{{ lookup('env', 'API_KEY') }}"
          VITE_BUILD_VERSION="{{ build_version }}"
        dest: /app/Frontend/.env
        mode: '0600'
        owner: azureuser
        group: azureuser

    # DEBUG - kan tas bort senare
    - name: Debug MongoDB Configuration
      ansible.builtin.debug:
        msg: |
          MONGODB_URI: {{ lookup('env', 'MONGODB_URI') }}
          MONGODB_DATABASE: {{ lookup('env', 'MONGODB_DATABASE') }}
          MONGODB_ADMIN: {{ lookup('env', 'MONGODB_ADMIN') }}

    # DEBUG - Verify all required files exist
    - name: Verify required files
      stat:
        path: "{{ item }}"
      register: file_checks
      with_items:
        - /app/.env
        - /app/Frontend/.env
        - /app/docker-compose.yml

    # Start application with new version
    - name: Start Docker Compose
      community.docker.docker_compose:
        project_src: /app
        build: yes
        pull: yes
        recreate: always
        build_args:
          BUILD_VERSION: "{{ build_version }}"