- name: Deploy Application
  hosts: app_server
  become: yes
  tasks:
    # Skip file copying since Act already does it
    - name: Verify Frontend directory exists
      stat:
        path: /app/Frontend
      register: frontend_dir

    - name: Fail if Frontend directory is missing
      fail:
        msg: "Frontend directory is missing"
      when: not frontend_dir.stat.isdir

    # Full Docker cleanup
    - name: Full Docker cleanup
      shell: |
        cd /app
        docker compose down --remove-orphans --volumes || true
        docker stop $(docker ps -aq) || true
        docker rm $(docker ps -aq) || true
        docker rmi $(docker images -q) || true
        docker system prune -af --volumes || true
      ignore_errors: yes

    # Create environment files
    - name: Create Backend .env file
      copy:
        content: |
          MONGODB_URI="{{ lookup('env', 'MONGODB_URI') }}"
          API_KEY="{{ lookup('env', 'API_KEY') }}"
          MONGODB_ADMIN="{{ lookup('env', 'MONGODB_ADMIN') }}"
          MONGODB_ADMIN_PASSWORD="{{ lookup('env', 'MONGODB_ADMIN_PASSWORD') }}"
          MONGODB_DATABASE="{{ lookup('env', 'MONGODB_DATABASE') }}"
        dest: /app/.env
        owner: azureuser
        group: azureuser
        mode: '0600'

    - name: Create Frontend .env file
      copy:
        content: |
          VITE_API_BASE_URL="http://{{ lookup('env', 'AZURE_VM_IP') }}/api"
          VITE_API_KEY="{{ lookup('env', 'API_KEY') }}"
        dest: /app/Frontend/.env
        owner: azureuser
        group: azureuser
        mode: '0600'

    # Create production settings from template
    - name: Create appsettings.Production.json from template
      template:
        src: "{{ playbook_dir }}/templates/appsettings.Production.json.j2"
        dest: /app/Backend/appsettings.Production.json
        mode: '0644'
        owner: azureuser
        group: azureuser
      vars:
        app_ip: "{{ lookup('env', 'VM_IP') }}"
        mongodb_uri: "{{ lookup('env', 'MONGODB_URI') }}"
        api_key: "{{ lookup('env', 'API_KEY') }}"

    - name: Debug MongoDB Configuration
      ansible.builtin.debug:
        msg: |
          MONGODB_URI: {{ lookup('env', 'MONGODB_URI') }}
          MONGODB_DATABASE: {{ lookup('env', 'MONGODB_DATABASE') }}
          MONGODB_ADMIN: {{ lookup('env', 'MONGODB_ADMIN') }}

    # Verify all required files exist
    - name: Verify required files
      stat:
        path: "{{ item }}"
      register: file_checks
      with_items:
        - /app/.env
        - /app/Frontend/.env
        - /app/Backend/appsettings.Production.json
        - /app/docker-compose.yml

    # Start application using Docker Compose
    - name: Start Docker Compose
      ansible.builtin.shell: |
        cd /app
        docker compose up -d --remove-orphans --force-recreate
      args:
        chdir: /app