---
- name: Configure application server
  hosts: app_server
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: ['docker.io', 'docker-compose-plugin']
        state: present
        update_cache: yes

    - name: Copy application files
      copy:
        src: ./
        dest: /app/
        owner: azureuser
        group: azureuser

    - name: Start Docker Compose
      community.docker.docker_compose_v2:
        project_src: /app
        files: [docker-compose.yml]
        state: present