name: Production Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'yarn'
          cache-dependency-path: Frontend/yarn.lock

      - name: Build & Test Backend
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet test Backend.Test/Backend.Test.csproj --configuration Release --verbosity normal

      - name: Build Frontend
        working-directory: Frontend
        run: |
          yarn install
          yarn build

  infrastructure:
    name: Infrastructure Setup
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/tbas_deploy_key
          chmod 600 ~/.ssh/tbas_deploy_key
          ssh-keygen -y -f ~/.ssh/tbas_deploy_key > ~/.ssh/tbas_deploy_key.pub
        working-directory: infrastructure/terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply
        working-directory: infrastructure/terraform
        run: |
          terraform init

          # Importera resource group
          terraform import azurerm_resource_group.main /subscriptions/831a771a-003a-4263-b2cf-fe3ef338dbca/resourceGroups/app-rg || true

          # Importera virtual network
          terraform import azurerm_virtual_network.main /subscriptions/831a771a-003a-4263-b2cf-fe3ef338dbca/resourceGroups/app-rg/providers/Microsoft.Network/virtualNetworks/app-rg-vnet || true

          # Importera public IP
          terraform import azurerm_public_ip.main /subscriptions/831a771a-003a-4263-b2cf-fe3ef338dbca/resourceGroups/app-rg/providers/Microsoft.Network/publicIPAddresses/app-rg-ip || true

          # Importera network security group
          terraform import azurerm_network_security_group.main /subscriptions/831a771a-003a-4263-b2cf-fe3ef338dbca/resourceGroups/app-rg/providers/Microsoft.Network/networkSecurityGroups/app-rg-nsg || true

          terraform apply -auto-approve

  deploy:
    name: Application Deployment
    needs: infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Ansible
        run: |
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt install ansible

      - name: Install Ansible collections
        run: ansible-galaxy collection install community.docker

      - name: Deploy with Ansible
        working-directory: infrastructure/ansible
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory.yml playbook.yml --private-key=ssh_key