name: Production Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'yarn'
          cache-dependency-path: 'Frontend/yarn.lock'

      - name: Build & Test Backend
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet test --configuration Release Backend.Test/Backend.Test.csproj --verbosity normal

      - name: Build Frontend
        working-directory: Frontend
        env:
          VITE_API_BASE_URL: "http://${{ secrets.AZURE_VM_IP }}/api"
          VITE_API_KEY: "${{ secrets.API_KEY }}"
        run: |
          yarn install --frozen-lockfile
          yarn build

  infrastructure:
    name: Azure Infrastructure Setup
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/tbas_deploy_key
          chmod 600 ~/.ssh/tbas_deploy_key
          ssh-keygen -y -f ~/.ssh/tbas_deploy_key > ~/.ssh/tbas_deploy_key.pub || true
        working-directory: infrastructure/terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply
        working-directory: infrastructure/terraform
        env:
          TF_VAR_AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
        run: |
          terraform init
          terraform import azurerm_resource_group.main /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/app-rg || true
          terraform import azurerm_virtual_network.main /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/app-rg/providers/Microsoft.Network/virtualNetworks/app-rg-vnet || true
          terraform import azurerm_subnet.main /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/app-rg/providers/Microsoft.Network/virtualNetworks/app-rg-vnet/subnets/internal || true
          terraform import azurerm_public_ip.main /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/app-rg/providers/Microsoft.Network/publicIPAddresses/app-rg-ip || true
          terraform import azurerm_network_security_group.main /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/app-rg/providers/Microsoft.Network/networkSecurityGroups/app-rg-nsg || true
          terraform import azurerm_network_interface.main /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/app-rg/providers/Microsoft.Network/networkInterfaces/app-rg-nic || true
          terraform import azurerm_linux_virtual_machine.main /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/app-rg/providers/Microsoft.Compute/virtualMachines/app-rg-vm || true
          terraform apply -auto-approve

  deploy:
    name: Deploy to Azure
    needs: infrastructure
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: mongodb://appuser:${{ secrets.MONGODB_PASSWORD }}@mongodb:27017/tbas_db?authSource=admin
      AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
      API_KEY: ${{ secrets.API_KEY }}
      MONGODB_USER: ${{ secrets.MONGODB_USER }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      MONGODB_ADMIN: ${{ secrets.MONGODB_ADMIN }}
      MONGODB_ADMIN_PASSWORD: ${{ secrets.MONGODB_ADMIN_PASSWORD }}
      MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ansible
        run: |
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y ansible

      - name: Force clean before deploy
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key
          ssh -i ssh_key -o StrictHostKeyChecking=no azureuser@${{ secrets.AZURE_VM_IP }} '
            cd /app
            docker compose down
            docker system prune -af
          '

      - name: Run Ansible Playbook
        working-directory: infrastructure/ansible
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory.yml playbook.yml --private-key=ssh_key